### ISSUE TITLE
Unexpected behavior when passing bad BLAST path

### ISSUE THREAD

**Issue by schackartk** [vanessajurtz/MetaPhinder#5]
When a path not containing BLASTi is passed as `-b`, the following occurs.

```
$ ./MetaPhinder.py -i phage_genomes/phages_1_hr.fsa -b ./no/blast/here -d database/ALL_140821_hr
parsing commandline options...
running BLAST...
sh: 1: ./no/blast/here/blastn: not found
calculating ANI...
Traceback (most recent call last):
  File "./MetaPhinder.py", line 228, in <module>
    if (old_id != str(l[0])) and (old_id != ""):
NameError: name 'l' is not defined
```

The shell process gives the message that blastn was not found. However, the program continues until it reaches an exception on line 228.

It would be best to exit the program with non-zero status as soon as BLAST was not found.

It may also be convenient to make this an optional argument, and see if BLAST can be found with `which blastn` as the default.

**Comment by schackartk** [comment]
Additionally, when the full path to blastn is passed, this also fails in the same way. It would be nice to have some flexibility to provide either BLAST parent directory or full path.

```
$ ./env/bin/blastn -version
blastn: 2.12.0+
 Package: blast 2.12.0, build Jul 13 2021 09:03:00

$ ./MetaPhinder.py -i phage_genomes/phages_1_hr.fsa -b ./env/bin/blastn -d database/ALL_140821_hr
parsing commandline options...
running BLAST...
sh: 1: ./env/bin/blastn/blastn: not found
calculating ANI...
Traceback (most recent call last):
  File "./MetaPhinder.py", line 228, in <module>
    if (old_id != str(l[0])) and (old_id != ""):
NameError: name 'l' is not defined
```
